@baseUrl = http://localhost:5050/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmJiNTNlMjFmYjljM2ViODAzYzY5NCIsImlhdCI6MTYxNzczMDExMn0.FeG2xzGt3iUyoZPhClcEJdc5l5mHCfHtu7AnejPKeyA

POST {{baseUrl}}/signup
Content-Type: application/json

{
    "name": "Ramon Admin",
    "email": "admin@mail.com",
    "password": "Ramon2",
    "passwordConfirmation": "Ramon2"
}

###

POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "Ramon2"
}

###

POST {{baseUrl}}/surveys
x-access-token: {{token}}
Content-Type: application/json

{
    "question": "question",
    "answers": [{
        "answer": "Answer 2",
        "image": "http://image-name.com"
        }
    ]
}

###

GET {{baseUrl}}/surveys 
x-access-token: {{token}}

###

PUT {{baseUrl}}/surveys/606bb64921fb9c3eb803c695/results
x-access-token: {{token}}
Content-Type: application/json

{
    "answer": "Answer 1"
}
